version: "2"
services:
    web:
        build: .
        container_name: listavip_server
        volumes:
            - /tmp/listavip:/tmp
            - ../target:/usr/src
        depends_on:
            - db
        network_mode: host

    db:
        image: mariadb:10.3
        container_name: listavip_db
        volumes:
            - ./mysql_data:/var/lib/mysql
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD="true"
        network_mode: host

networks:
    default:
        external:
            name: "host"
